#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Dec 14 04:59:35 GMT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Solas Shader V3.1c.zip
enableShaders=true
